# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvuP66G34NgnseeWmr-X4vSzykKoY29T
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained fraud detection model
with open("fraud_model.pkl", "rb") as f:
    model = pickle.load(f)

st.title("💳 Fraud Transaction Detection System")

st.write("Enter transaction details below to check if it’s fraudulent or not:")

# Input fields for 9 features
amount = st.number_input("Transaction Amount", min_value=0.0, step=0.1)
customer_id = st.number_input("Customer ID", min_value=1, step=1)
terminal_id = st.number_input("Terminal ID", min_value=1, step=1)
hour = st.number_input("Transaction Hour", min_value=0, max_value=23, step=1)
day = st.number_input("Transaction Day", min_value=1, max_value=31, step=1)
month = st.number_input("Transaction Month", min_value=1, max_value=12, step=1)
year = st.number_input("Transaction Year", min_value=2000, max_value=2100, step=1)
latitude = st.number_input("Latitude", step=0.0001, format="%.4f")
longitude = st.number_input("Longitude", step=0.0001, format="%.4f")

# Collect features in the SAME ORDER as training
features = np.array([[amount, customer_id, terminal_id, hour, day, month, year, latitude, longitude]])

if st.button("🔍 Predict"):
    try:
        prediction = model.predict(features)[0]
        if prediction == 1:
            st.error("⚠️ Fraudulent Transaction Detected!")
        else:
            st.success("✅ Legitimate Transaction")
    except Exception as e:
        st.error(f"Error: {e}")